// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pmo;

namespace pmo.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20200213120259_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("dbModels.BusinessCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddToTecnicalAbilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Changes")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerMarketAnalysis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataStartingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GpaRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MultipleFieldsGeneratedTable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumberOfYears")
                        .HasColumnType("int");

                    b.Property<decimal>("ProbabiltyOfWin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ProjectCompletion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectScope")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<bool>("StrategicAlignment")
                        .HasColumnType("bit");

                    b.Property<decimal>("TargetFirstYearGrossMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TimeFromProjectCompletionToRevenueGeneration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<bool>("WillCustomerFundQual")
                        .HasColumnType("bit");

                    b.Property<bool>("WillCustomerFundTooling")
                        .HasColumnType("bit");

                    b.Property<decimal>("WorkRequirementAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WorkRequirementUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("BusinessCases");
                });

            modelBuilder.Entity("dbModels.BusinessCase_ManufacturingLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusinessCaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ManufacturingLocationsTagId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessCaseId");

                    b.HasIndex("ManufacturingLocationsTagId");

                    b.ToTable("BusinessCase_ManufacturingLocations");
                });

            modelBuilder.Entity("dbModels.CustomerDesignApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSentForApprove")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentForApprovalBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("CustomerDesignApprovals");
                });

            modelBuilder.Entity("dbModels.DeliverableRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.HasIndex("TagId");

                    b.ToTable("DeliverableRegisters");
                });

            modelBuilder.Entity("dbModels.DeliverableRegisterConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.HasIndex("TagId");

                    b.ToTable("DeliverableRegisterConfigs");
                });

            modelBuilder.Entity("dbModels.Gate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActualReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Gates");
                });

            modelBuilder.Entity("dbModels.GateApprovers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GateApproverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GateId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GateId");

                    b.ToTable("GateApprovers");
                });

            modelBuilder.Entity("dbModels.GateConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GateNumber")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GateConfigs");
                });

            modelBuilder.Entity("dbModels.GateKeeperConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GateConfigId")
                        .HasColumnType("int");

                    b.Property<string>("Keeper")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GateConfigId");

                    b.ToTable("GateKeeperConfigs");
                });

            modelBuilder.Entity("dbModels.InvestmentPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchasedFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipToLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<string>("Terms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("InvestmentPlans");
                });

            modelBuilder.Entity("dbModels.KeyCharacteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpectedOutcomeRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("MeasuredValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequirementSourceId")
                        .HasColumnType("int");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequirementSourceId");

                    b.HasIndex("StageId");

                    b.ToTable("KeyCharacteristics");
                });

            modelBuilder.Entity("dbModels.Mitigation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("MitigationPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RiskId");

                    b.ToTable("Mitigations");
                });

            modelBuilder.Entity("dbModels.ProductInfrigmentPatentability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ContainsFeaturesRequiringIPProtection")
                        .HasColumnType("bit");

                    b.Property<bool>("ContainsInfingmentIssues")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("InventionDisclosureSubmitted")
                        .HasColumnType("bit");

                    b.Property<string>("Issue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("MitigationStrategy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductFirstTimeOfferedForSale")
                        .HasColumnType("datetime2");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("ProductInfrigmentPatentabilities");
                });

            modelBuilder.Entity("dbModels.ProductIntroChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ApprovedByDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Filename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMarketingRequired")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("ProductIntroChecklists");
                });

            modelBuilder.Entity("dbModels.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("dbModels.ProjectDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DesignAuthorityTagId")
                        .HasColumnType("int");

                    b.Property<string>("EndUseDestinationCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineeringChecklistUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExportApplicationTypeTagId")
                        .HasColumnType("int");

                    b.Property<string>("ExportControlCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductLineTagId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectCategoryTagId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectClassificationTagId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectProcessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesforce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DesignAuthorityTagId");

                    b.HasIndex("ExportApplicationTypeTagId");

                    b.HasIndex("ProductLineTagId");

                    b.HasIndex("ProjectCategoryTagId");

                    b.HasIndex("ProjectClassificationTagId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectDetails");
                });

            modelBuilder.Entity("dbModels.ProjectDetail_Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomersTagId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomersTagId");

                    b.HasIndex("ProjectDetailId");

                    b.ToTable("ProjectDetail_Customers");
                });

            modelBuilder.Entity("dbModels.ProjectDetail_EndUserCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EndUserCountriesTagId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EndUserCountriesTagId");

                    b.HasIndex("ProjectDetailId");

                    b.ToTable("ProjectDetail_EndUserCountries");
                });

            modelBuilder.Entity("dbModels.ProjectDetail_SalesRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectDetailId")
                        .HasColumnType("int");

                    b.Property<int>("SalesRegionTagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectDetailId");

                    b.HasIndex("SalesRegionTagId");

                    b.ToTable("ProjectDetail_SalesRegions");
                });

            modelBuilder.Entity("dbModels.ProjectJustification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AddToInhouseTechnicalAbilities")
                        .HasColumnType("bit");

                    b.Property<string>("AdvantagesWeOffer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Application")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BenchmarkSamples")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Competetion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerMotivation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrawingSpecStandards")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductTagId")
                        .HasColumnType("int");

                    b.Property<string>("RegulatoryRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scope")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SingleUseProduct")
                        .HasColumnType("bit");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<string>("TechnicalFeasibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("WhyOurOfferPreferred")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductTagId");

                    b.HasIndex("StageId");

                    b.ToTable("ProjectJustifications");
                });

            modelBuilder.Entity("dbModels.ProjectStateHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectState")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectStateHistories");
                });

            modelBuilder.Entity("dbModels.Project_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobDescriptionKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Project_User");
                });

            modelBuilder.Entity("dbModels.QualificationTesting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsQualificationRequired")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("QualificationTestings");
                });

            modelBuilder.Entity("dbModels.RampResourcePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("RampResourcePlans");
                });

            modelBuilder.Entity("dbModels.Risk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskImpactTagId")
                        .HasColumnType("int");

                    b.Property<decimal>("RiskPropability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RiskTypeTagId")
                        .HasColumnType("int");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RiskImpactTagId");

                    b.HasIndex("RiskTypeTagId");

                    b.HasIndex("StageId");

                    b.ToTable("Risks");
                });

            modelBuilder.Entity("dbModels.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CanInitiateProject")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ManagesBusinessCases")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagesCustomerDesignApproval")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagesDeliverableRegister")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagesDeliverableRegisters")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagesIntellectualProperty")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagesInvestmentPlan")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagesMarketingPlan")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagesParts")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagesPauseProject")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagesProjectDetail")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagesProjectRequirements")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagesProjectTeam")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagesQualificationTesting")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagesRampAndResourcePlan")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagesRiskAnalysis")
                        .HasColumnType("bit");

                    b.Property<bool>("ManagesScheduling")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("dbModels.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.HasIndex("TagId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("dbModels.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("StageNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("dbModels.StageConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AllowInsertRiskAssesments")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MinBusinessCases")
                        .HasColumnType("int");

                    b.Property<int>("MinCustomerDesignApprovals")
                        .HasColumnType("int");

                    b.Property<int>("MinDesignConcepts")
                        .HasColumnType("int");

                    b.Property<int>("MinInvestmentPlans")
                        .HasColumnType("int");

                    b.Property<int>("MinKeyCharacteristics")
                        .HasColumnType("int");

                    b.Property<int>("MinProductInfringementPatentabilities")
                        .HasColumnType("int");

                    b.Property<int>("MinProductIntroChecklist")
                        .HasColumnType("int");

                    b.Property<int>("MinProjectJustifications")
                        .HasColumnType("int");

                    b.Property<int>("MinQualificationTesting")
                        .HasColumnType("int");

                    b.Property<int>("MinRampResourcePlans")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StageNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StageConfigs");
                });

            modelBuilder.Entity("dbModels.StageConfig_RequiredSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequiredScheduleTagId")
                        .HasColumnType("int");

                    b.Property<int>("StageConfigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequiredScheduleTagId");

                    b.HasIndex("StageConfigId");

                    b.ToTable("StageConfig_RequiredSchedules");
                });

            modelBuilder.Entity("dbModels.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TagCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TagCategoryId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("dbModels.TagCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TagCategories");
                });

            modelBuilder.Entity("dbModels.UploadedDocumentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UploadedDocumentation");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UploadedDocumentation");
                });

            modelBuilder.Entity("dbModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetworkUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("dbModels.User_CitizenShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCitizenShip");
                });

            modelBuilder.Entity("dbModels.CustomerDesignApprovalUploadedDocumentation", b =>
                {
                    b.HasBaseType("dbModels.UploadedDocumentation");

                    b.Property<int>("CustomerDesignApprovalId")
                        .HasColumnType("int");

                    b.HasIndex("CustomerDesignApprovalId");

                    b.HasDiscriminator().HasValue("CustomerDesignApprovalUploadedDocumentation");
                });

            modelBuilder.Entity("dbModels.GateUploadedDocumentation", b =>
                {
                    b.HasBaseType("dbModels.UploadedDocumentation");

                    b.Property<int>("GateId")
                        .HasColumnType("int");

                    b.HasIndex("GateId");

                    b.HasDiscriminator().HasValue("GateUploadedDocumentation");
                });

            modelBuilder.Entity("dbModels.ProductInfrigmentPatentabilityUploadedDocumentation", b =>
                {
                    b.HasBaseType("dbModels.UploadedDocumentation");

                    b.Property<int>("ProductInfrigmentPatentabilityId")
                        .HasColumnType("int");

                    b.HasIndex("ProductInfrigmentPatentabilityId");

                    b.HasDiscriminator().HasValue("ProductInfrigmentPatentabilityUploadedDocumentation");
                });

            modelBuilder.Entity("dbModels.BusinessCase", b =>
                {
                    b.HasOne("dbModels.Stage", "Stage")
                        .WithMany("BusinessCaseHistory")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.BusinessCase_ManufacturingLocation", b =>
                {
                    b.HasOne("dbModels.BusinessCase", "BusinessCase")
                        .WithMany("ManufacturingLocations")
                        .HasForeignKey("BusinessCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.Tag", "ManufacturingLocations")
                        .WithMany()
                        .HasForeignKey("ManufacturingLocationsTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.CustomerDesignApproval", b =>
                {
                    b.HasOne("dbModels.Stage", "Stage")
                        .WithMany("CustomerDesignApprovalHistory")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.DeliverableRegister", b =>
                {
                    b.HasOne("dbModels.Stage", "Stage")
                        .WithMany("DeliverableRegisters")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.Tag", "DeliverableRegisterTag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.DeliverableRegisterConfig", b =>
                {
                    b.HasOne("dbModels.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.Tag", "DeliverableRegisterTag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.Gate", b =>
                {
                    b.HasOne("dbModels.Project", "Project")
                        .WithMany("GateHistory")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.GateApprovers", b =>
                {
                    b.HasOne("dbModels.Gate", "Gate")
                        .WithMany("GateApprover")
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.GateKeeperConfig", b =>
                {
                    b.HasOne("dbModels.GateConfig", "GateConfig")
                        .WithMany("GateKeepers")
                        .HasForeignKey("GateConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.InvestmentPlan", b =>
                {
                    b.HasOne("dbModels.Stage", "Stage")
                        .WithMany("InvestmentPlanHistory")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.KeyCharacteristic", b =>
                {
                    b.HasOne("dbModels.Tag", "RequirementSource")
                        .WithMany()
                        .HasForeignKey("RequirementSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.Stage", "Stage")
                        .WithMany("KeyCharacteristicHistory")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.Mitigation", b =>
                {
                    b.HasOne("dbModels.Risk", "Risk")
                        .WithMany()
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.ProductInfrigmentPatentability", b =>
                {
                    b.HasOne("dbModels.Stage", "Stage")
                        .WithMany("ProductInfrigmentPatentabilityHistory")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.ProductIntroChecklist", b =>
                {
                    b.HasOne("dbModels.Stage", "Stage")
                        .WithMany("ProductIntroChecklistHistory")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.ProjectDetail", b =>
                {
                    b.HasOne("dbModels.Tag", "DesignAuthority")
                        .WithMany()
                        .HasForeignKey("DesignAuthorityTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.Tag", "ExportApplicationType")
                        .WithMany()
                        .HasForeignKey("ExportApplicationTypeTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.Tag", "ProductLine")
                        .WithMany()
                        .HasForeignKey("ProductLineTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.Tag", "ProjectCategory")
                        .WithMany()
                        .HasForeignKey("ProjectCategoryTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.Tag", "ProjectClassification")
                        .WithMany()
                        .HasForeignKey("ProjectClassificationTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.Project", "Project")
                        .WithMany("ProjectDetail")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.ProjectDetail_Customer", b =>
                {
                    b.HasOne("dbModels.Tag", "Customers")
                        .WithMany()
                        .HasForeignKey("CustomersTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.ProjectDetail", "ProjectDetail")
                        .WithMany("Customers")
                        .HasForeignKey("ProjectDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.ProjectDetail_EndUserCountry", b =>
                {
                    b.HasOne("dbModels.Tag", "EndUserCountries")
                        .WithMany()
                        .HasForeignKey("EndUserCountriesTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.ProjectDetail", "ProjectDetail")
                        .WithMany("EndUseCountries")
                        .HasForeignKey("ProjectDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.ProjectDetail_SalesRegion", b =>
                {
                    b.HasOne("dbModels.ProjectDetail", "ProjectDetail")
                        .WithMany("SalesRegions")
                        .HasForeignKey("ProjectDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.Tag", "SalesRegion")
                        .WithMany()
                        .HasForeignKey("SalesRegionTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.ProjectJustification", b =>
                {
                    b.HasOne("dbModels.Tag", "Product")
                        .WithMany()
                        .HasForeignKey("ProductTagId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("dbModels.Stage", "Stage")
                        .WithMany("ProjectJustificationHistory")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.ProjectStateHistory", b =>
                {
                    b.HasOne("dbModels.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.Project_User", b =>
                {
                    b.HasOne("dbModels.Project", "Project")
                        .WithMany("TeamMember")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.QualificationTesting", b =>
                {
                    b.HasOne("dbModels.Stage", "Stage")
                        .WithMany("QualificationTestingHistory")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.RampResourcePlan", b =>
                {
                    b.HasOne("dbModels.Stage", "Stage")
                        .WithMany("RampResourcePlanHistory")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.Risk", b =>
                {
                    b.HasOne("dbModels.Tag", "RiskImpact")
                        .WithMany()
                        .HasForeignKey("RiskImpactTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.Tag", "RiskType")
                        .WithMany()
                        .HasForeignKey("RiskTypeTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.Stage", "Stage")
                        .WithMany("Risks")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.Schedule", b =>
                {
                    b.HasOne("dbModels.Stage", "Stage")
                        .WithMany("Schedules")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.Tag", "ScheduleType")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.Stage", b =>
                {
                    b.HasOne("dbModels.Project", "Project")
                        .WithMany("StageHistory")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.StageConfig_RequiredSchedule", b =>
                {
                    b.HasOne("dbModels.Tag", "RequiredSchedule")
                        .WithMany()
                        .HasForeignKey("RequiredScheduleTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.StageConfig", "StageConfig")
                        .WithMany("RequiredSchedules")
                        .HasForeignKey("StageConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.Tag", b =>
                {
                    b.HasOne("dbModels.TagCategory", "TagCategory")
                        .WithMany("Tags")
                        .HasForeignKey("TagCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.User", b =>
                {
                    b.HasOne("dbModels.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.User_CitizenShip", b =>
                {
                    b.HasOne("dbModels.Tag", "Citizenships")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dbModels.User", "User")
                        .WithMany("Citizenships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.CustomerDesignApprovalUploadedDocumentation", b =>
                {
                    b.HasOne("dbModels.CustomerDesignApproval", "CustomerDesignApproval")
                        .WithMany("ImportantDocumentation")
                        .HasForeignKey("CustomerDesignApprovalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.GateUploadedDocumentation", b =>
                {
                    b.HasOne("dbModels.Gate", "Gate")
                        .WithMany("GateUploadedDocumentation")
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dbModels.ProductInfrigmentPatentabilityUploadedDocumentation", b =>
                {
                    b.HasOne("dbModels.ProductInfrigmentPatentability", "ProductInfrigmentPatentability")
                        .WithMany("ProductInfrigmentPatentabilityImportantDocumentation")
                        .HasForeignKey("ProductInfrigmentPatentabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
